### ISSUE TITLE
Save Data to Database.

### ISSUE THREAD

**Issue by bhavinshahcin7** [thanhtunguet/grapesjs-react#14]
Hello, I would like to save the HTML and CSS, both into database. How I can do that? 
Apart from that I am not able to drag and drop or upload an image into editor.

Any help would be great.
Thank You.

**Comment by thanhtunguet** [comment]
Hello,
According to the official docs of GrapesJS ([https://grapesjs.com/docs/modules/Storage.html#basic-configuration](https://grapesjs.com/docs/modules/Storage.html#basic-configuration)). You can pass a storeManager configuration to the editor like below:

```javascript
const  storageManager = {
    type: 'remote',
    stepsBeforeSave: 3,
    urlStore: 'http://endpoint/store-template/some-id-123',
    urlLoad: 'http://endpoint/load-template/some-id-123',
    // For custom parameters/headers on requests
    params: { _some_token: '....' },
    headers: { Authorization: 'Basic ...' },
  };
```
You can pass your API URL to store the template using `urlStore` and `urlLoad` property.
Then, you initiate your editor and pass the storeManager configuration as a prop

**Comment by bhavinshahcin7** [comment]
Thank you for your reply. I am using grapesjs-react npm plugin. 
How can I use StoreManager in that ?

Thank You.

**Comment by thanhtunguet** [comment]
Hi,
See my example below:

![image](https://user-images.githubusercontent.com/22119727/63769040-f6888780-c8fb-11e9-87e6-6cb8d7a14b95.png)

**Comment by thanhtunguet** [comment]
Sorry, you need to specify storage type as `remote`:

![image](https://user-images.githubusercontent.com/22119727/63770040-76175600-c8fe-11e9-8ce5-f9b65614f83c.png)
