### ISSUE TITLE
Multiple copies of react with recent update

### ISSUE THREAD

**Issue by l3aconator** [thanhtunguet/grapesjs-react#15]
Howdy! Awesome to see hooks being used in this project. I noticed that `react` and `react-dom` aren't peerDependencies so it makes React think there are multiple copies of it. 

Workaround is to `npm link react` and `npm link react-dom` from the project root AND the root of the installed module and was able to get the editor to load.

Also, in your example you import directly from the repo, which works but the it looks like `import { Editor } from 'grapesjs-react';` or `import { GEditor } from 'grapesjs-react';` is the way we have to import externally, the readme needs to be updated. 

Cool package! looking forward to working with it.

**Comment by thanhtunguet** [comment]
Thank you for your report. I have updated the package according to your guide. Please check the newest version.

**Comment by abhishekchotaliya** [comment]
This issue is still happening

**Comment by thanhtunguet** [comment]
> This issue is still happening

Please give me a detailed reproduction of this issue.
