### ISSUE TITLE
Add props.children to GEditor

### ISSUE THREAD

**Issue by beepsoft** [thanhtunguet/grapesjs-react#16]
Hi,

it would be great if we could provide the initial content of the editor as the children of the GEditor like this:

```
 <GEditor id="geditor" newsletter={true}>
  <div>This is my initial editor content</div>
</GEditor>
```

I think it would only take 2 lines in GEditor.tsx to add children property to  IProps and then include the children at the end in the div returned:

```
interface IProps {
  ...
  children?: any;
}

function GEditor(props: IProps) {
  ...
  return <div id={id}>{props.children ? props.children : null}</div>;
}
```

**Comment by thanhtunguet** [comment]
It is awesome feature :) But please read my 2 comments and modify your code before I accept your pull request to simplify the code and clearly illustrate the feature that you want to add
