### ISSUE TITLE
Add callback to get the GrapesJS editor instance from GEditor

### ISSUE THREAD

**Issue by beepsoft** [thanhtunguet/grapesjs-react#19]
Hi,

I would be great if we had a property of GEditor where we could provide a function, which would be called once GEditor finished configuring the wrapped GrapesJS editor instance. Something like:

```
   <GEditor editorConfigured={setEditor}/>
```

This way the component creating the GEditor would have an easy access to the  GrapesJS editor to further configure it.

What do you think?

**Comment by thanhtunguet** [comment]
I think it will be useful. Please implement this and create a pull request to make your idea come true.
