### ISSUE TITLE
Import broken when trying to add GEditor 

### ISSUE THREAD

**Issue by bumpradar** [thanhtunguet/grapesjs-react#23]
Unhandled Rejection (Error): Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

import React from 'react';
import { GEditor } from 'grapesjs-react'

export default () => {

return (
    <GEditor />
    
);
}

**Comment by thanhtunguet** [comment]
Sorry, the API of v3 was changed. Please import {Editor} instead of {GEditor}
