### ISSUE TITLE
Drag/Drop in Editor instantiated with grapesjs-mjml plugin not working

### ISSUE THREAD

**Issue by sahsharm** [thanhtunguet/grapesjs-react#26]
Hi,
Drag and Drop of any MJML block on the canvas fails with the following warning:-
**Target collection not found, Target is not droppable, accepts [undefined], Component not draggable, acceptable by [undefined]**

**Comment by sahsharm** [comment]
Hi Team,
Can anybody please respond ?
Thanks,
Sahil

**Comment by thanhtunguet** [comment]
Hi @sahsharm , please read the official documentation of grapesjs and config your editor by passing onInit function prop

**Comment by sahsharm** [comment]
Hi @thanhtunguet, thank you for replying. 

This is what I have been trying to do. Not sure where I am going wrong.

import React from 'react';
import './App.css';
import {Editor} from 'grapesjs-react';
function App() {
  return (
    <Editor plugins={["grapesjs-mjml"]}/>
  );
}
export default App;
-----
Index.html grapejs dependencies
<link href="https://unpkg.com/grapesjs/dist/css/grapes.min.css" rel="stylesheet">
<script src="https://unpkg.com/grapesjs"></script>
<script src="dist/grapesjs-mjml.min.js"></script>

**Comment by sahsharm** [comment]
Drag and Drop in default editor without the plugins property works fine.

**Comment by thanhtunguet** [comment]
> Drag and Drop in default editor without the plugins property works fine.

Did you passed both plugins mjml as a string and presetType? It may caused that error

**Comment by sahsharm** [comment]
No, I just passed the plugins, it will be really helpful if you can paste the recommended configuration here.

**Comment by sahsharm** [comment]
Hi @thanhtunguet , if you could please help in resolving this.

**Comment by thanhtunguet** [comment]
@sahsharm Can you help me solving this? 
I am a little bit busy and do not have time to solve issues of this package

**Comment by thanhtunguet** [comment]
@sahsharm  Have you try this:

```jsx
<Editor presetType="mjml" />
```

**Comment by buzztnt** [comment]
@sahsharm did you ever find a solution to this ?
