### ISSUE TITLE
drag'n'drop broken with MJML preset 

### ISSUE THREAD

**Issue by DigiPascal** [thanhtunguet/grapesjs-react#31]
Hi,

I have an issue when using the MJML preset. I think When I use preset newsletter everything is fine when I switch to MJML, I have the editor loading without any error but it not possible to drag n drop anything into the content (content does not add).

I guess the initialisation is not correct, because when I select the source in the editor. I get a strange output in the mjml code section (should be mjml instead): 
![image](https://user-images.githubusercontent.com/19272806/74805763-647a9e00-52e4-11ea-8c47-93ccf734b126.png)

This is my editor settings : 
```
import React from 'react';
import 'grapesjs/dist/css/grapes.min.css';
import {Editor} from 'grapesjs-react';
import {grapesJSMJML} from 'grapesjs-mjml';
import './App.css';

Editor.defaultProps = {
  id: 'grapesjs-react-editor',
  presetType: 'mjml',
  plugins: [grapesJSMJML],
  pluginsOpts: {
     [grapesJSMJML]: { }
  },
  blocks: [],
  blockManager: {},
  storageManager: {},
  styleManager: {},
  width: 'auto',
  height: '100vh',
};

function App() {
  return (
    <div className="App">
      <Editor />
    </div>
  );
}
export default App;
```

**Comment by thanhtunguet** [comment]
Duplicated of #26
