### ISSUE TITLE
I can't start my ReactJs app when add Grapesjs.

### ISSUE THREAD

**Issue by Spaske19911** [thanhtunguet/grapesjs-react#32]
<--- Last few GCs --->

[5930:0x102802000]    42499 ms: Scavenge 1370.6 (1421.3) -> 1369.8 (1421.8) MB, 6.6 / 0.0 ms  (average mu = 0.195, current mu = 0.128) allocation failure 
[5930:0x102802000]    44135 ms: Mark-sweep 1370.0 (1421.8) -> 1369.8 (1418.8) MB, 1635.1 / 0.0 ms  (average mu = 0.127, current mu = 0.052) allocation failure GC in old space requested
[5930:0x102802000]    44176 ms: Scavenge 1375.4 (1423.3) -> 1374.4 (1423.8) MB, 13.5 / 0.0 ms  (average mu = 0.127, current mu = 0.052) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3b9e0575be3d]
Security context: 0x01d6f0b1e6e9 <JSObject>
    1: SourceMapConsumer_allGeneratedPositionsFor [0x1d6323f89b1] [/Users/macbook/Documents/Poso/Web/XCUBE/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:~178] [pc=0x3b9e063164db](this=0x01d69cb02309 <BasicSourceMapConsumer map = 0x1d6399a6011>,aArgs=0x01d60ec11451 <Object map = 0x1d6399a4e31>)
    2: /* anonymous */(aka /* anony...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cff5 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1ff node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b8265 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1005861c2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588c95 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100584b3f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x100582d14 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058f5ac v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058f62f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10055ef74 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x1007e7254 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x3b9e0575be3d 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x-cube@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the x-cube@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook/.npm/_logs/2020-02-24T11_20_10_567Z-debug.log

When I remove Grapesjs, everything works fine!!!

**Comment by thanhtunguet** [comment]
Can you reproduce this issue by providing a Code sandbox?

**Comment by 0000marcell** [comment]
@Spaske19911 I had the same issue, i've solve it by deleting "package-lock.json" from my repository and then running "npm install"

**Comment by 0000marcell** [comment]
@thanhtunguet I couldn't repreduce it in code sandbox, but everytime you create a new react app with "create-react-app" you get the same problem, you can test it for yourself

**Comment by 0000marcell** [comment]
@thanhtunguet steps to reproduce it
```
npx create-react-app my-app
cd ./my-app
npm i grapesjs-react --save
npm start
```
the build will fail

**Comment by thanhtunguet** [comment]
@Spaske19911  @0000marcell  

I have tested. It works. Please check it again.
