### ISSUE TITLE
How can I add custom css file to geditor.

### ISSUE THREAD

**Issue by coldorbit** [thanhtunguet/grapesjs-react#33]
Is there any possibility to add external css to grapes editor?

In original grapesjs, we can import external css file like this.
```
var editor = grapesjs.init({
  ...
  canvas: {
    styles: [
      'https://...',
      ...
    ]
  }
});
```

How can I approach this in grapes-react library?

**Comment by thanhtunguet** [comment]
Please just import and customize CSS or SCSS normally!
