### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by thanhtunguet** [thanhtunguet/grapesjs-react#35]
I wrote this package more than one year ago. It is a part of a commercial product and
I decided to share this package with community.
I am very happy that my work is useful and used by other open source projects on GitHub.
However, I do not have enough time to maintain this package and reply to issues.
I don't want people who opened issues have to wait for my response for long time.

So I wish that if there is one of who used this packages, have time and understand how's Grapesj works, help me to maintain this package for our community.

I would be thankful.

**Comment by diegocabrito** [comment]
Do not take this package down, if it really works you will soon find someone who can help you effectively. I'm going to run your code now and see what I can do with it. Anyway thank you for having it available yet.

**Comment by diegocabrito** [comment]
> Do not take this package down, if it really works you will soon find someone who can help you effectively. I'm going to run your code now and see what I can do with it. Anyway thank you for having it available yet.

Could you make the demo available to us? You have some code example? Thanks.

**Comment by thanhtunguet** [comment]
> > Do not take this package down, if it really works you will soon find someone who can help you effectively. I'm going to run your code now and see what I can do with it. Anyway thank you for having it available yet.
> 
> Could you make the demo available to us? You have some code example? Thanks.

Please see the storybook demo of the Editor component [https://github.com/thanhtunguet/grapesjs-react/blob/master/src/Editor/Editor.stories.tsx](https://github.com/thanhtunguet/grapesjs-react/blob/master/src/Editor/Editor.stories.tsx)

**Comment by thanhtunguet** [comment]
> > Do not take this package down, if it really works you will soon find someone who can help you effectively. I'm going to run your code now and see what I can do with it. Anyway thank you for having it available yet.
> 
> Could you make the demo available to us? You have some code example? Thanks.

This package is tiny so you can just read the source code of Editor component and its interface. :D

**Comment by diegocabrito** [comment]
> > > Não retire este pacote, se ele realmente funcionar, você encontrará em breve alguém que poderá ajudá-lo de forma eficaz. Vou executar seu código agora e ver o que posso fazer com ele. De qualquer forma, obrigado por tê-lo disponível ainda.
> > 
> > 
> > Você poderia disponibilizar a demo para nós? Você tem algum exemplo de código? Obrigado.
> 
> Este pacote é pequeno, então você pode apenas ler o código fonte do componente Editor e sua interface. : D


is not a functional package?

**Comment by NotMoni** [comment]
@thanhtunguet Hey, mate I can help. Feel free to contact me. 🦄

**Comment by thanhtunguet** [comment]
> > > > Não retire este pacote, se ele realmente funcionar, você encontrará em breve alguém que poderá ajudá-lo de forma eficaz. Vou executar seu código agora e ver o que posso fazer com ele. De qualquer forma, obrigado por tê-lo disponível ainda.
> > > 
> > > 
> > > Você poderia disponibilizar a demo para nós? Você tem algum exemplo de código? Obrigado.
> > 
> > 
> > Este pacote é pequeno, então você pode apenas ler o código fonte do componente Editor e sua interface. : D
> 
> is not a functional package?

Sorry I do not understand what you mean.

**Comment by thanhtunguet** [comment]
> @thanhtunguet Hey, mate I can help. Feel free to contact me. 🦄

Thank you so much. If you can help me to maintain this package. I will send you contributor invitation. Please accept and help me replying issues, fixing bugs and adding new features.

**Comment by NotMoni** [comment]
I can try my best mate :D

**Comment by RobinLebhar** [comment]
Hey, I just want to mention that the storybook seems broken

https://grapesjs-react.thanhtunguet.info/?path=/story/*

cheers :)

**Comment by thanhtunguet** [comment]
> Hey, I just want to mention that the storybook seems broken
> 
> https://grapesjs-react.thanhtunguet.info/?path=/story/*
> 
> cheers :)

Thank you. It has been fixed :)

**Comment by udaypydi** [comment]
@thanhtunguet Are you still looking for maintainers. I can help you with that.

Thanks!

**Comment by thanhtunguet** [comment]
> @thanhtunguet Are you still looking for maintainers. I can help you with that.
> 
> Thanks!


Thank you. I have invited you as a collaborator of this repository. Please check and accept my invitation.

**Comment by udaypydi** [comment]
Thanks for inviting me @thanhtunguet . I have accepted the invite!

**Comment by udaypydi** [comment]
@thanhtunguet can we use this discord for communication and prioritizing the issues : https://discord.gg/R8CREQ?

**Comment by mr-ravi26** [comment]
Hey, I am using this application in one of my project, I want to contribute also, let me know if you are still looking out for it.

**Comment by thanhtunguet** [comment]
> @thanhtunguet can we use this discord for communication and prioritizing the issues : https://discord.gg/R8CREQ?

Just do it if it is easier for you to manager issues.

**Comment by thanhtunguet** [comment]
> Hey, I am using this application in one of my project, I want to contribute also, let me know if you are still looking out for it.

Thank you. If you want to contribute, fork this to your personal GitHub account, commit your code, and create a pull request back to this repository. If you want to become a maintainer, please send me an email to ht@thanhtunguet.info. Cheers!
