### ISSUE TITLE
Default Blocks Showing Characters e.g. W, Q, E, R rather then icons 

### ISSUE THREAD

**Issue by pravalj** [thanhtunguet/grapesjs-react#38]
I am using this editor in my project. It is very well designed.

One issue I am facing here in the block section.

I am getting alphabet characters like Q, W, E. R in place of Icons by default.

here you can check on the right side block

https://grapesjs-react.thanhtunguet.info/?path=/story/editor--newslettereditor

required one => https://grapesjs.com/demo-newsletter-editor.html

Is there any default setting change so I can get the icons by default?

**Comment by thanhtunguet** [comment]
This package is just a wrapper component of GrapesJS editor. I don't know why you got this issue.
Please check the documentation of GrapesJS for more details.
If you want to help, just create a pull request. Thank you
