### ISSUE TITLE
GBlock Export Issue

### ISSUE THREAD

**Issue by Anubhavjain786** [thanhtunguet/grapesjs-react#39]
How can I get GBlock from package, in .js Files. for reference, I use WIKI Section

**Comment by Anubhavjain786** [comment]
Hello Anyone is here to respond?

**Comment by thanhtunguet** [comment]
Sorry for the out-dated wiki. Please read the README file for v3 usage

**Comment by thanhtunguet** [comment]
Beside, none of my actual projects uses this package. So I do not know exactly what exactly people expect from this package. Can you contribute?

**Comment by Anubhavjain786** [comment]
yes sure, I have used grapesjs in very large about in my some of the project which is based on react.

**Comment by thanhtunguet** [comment]
> yes sure, I have used grapesjs in very large about in my some of the project which is based on react.

Please contribute your code by creating pull request!
