### ISSUE TITLE
SVG classes bugs

### ISSUE THREAD

**Issue by jeffersoncostameta** [thanhtunguet/grapesjs-react#44]
![Capturar](https://user-images.githubusercontent.com/54819227/102619511-56bbc200-411b-11eb-9e7d-64039731d777.PNG)

Hi,

I'm having trouble styling components in firefox

In the option 'open style manager', it's possible to add a class by clicking on the plus sign, edit this class and delete. These three SVG icons are unconfigured in firefox

See in the demo:

https://grapesjs-react.thanhtunguet.info/?path=/story/editor--newslettereditor

**Comment by thanhtunguet** [comment]
Please update to the latest version to see if the issue has been fixed or not
