### ISSUE TITLE
nameof is not defined

### ISSUE THREAD

**Issue by phuongEts** [thanhtunguet/grapesjs-react#48]
i have issue when install grapesjs react. when i build app it throw bugs "nameof is not defined". please help me fix it!

**Comment by thanhtunguet** [comment]
Please show the error log to help me know what is happening to you.

**Comment by Niush** [comment]
This is the line causing the issue in version "3.1.2". Causing ``nameof is not defined``.

https://github.com/thanhtunguet/grapesjs-react/blob/b516f45e127c0a5e323f9cc9b2b1a89436e88687/src/Editor/Editor.tsx#L130

**Comment by thanhtunguet** [comment]
Please try to upgrade to new version to see if the issue was resolved

**Comment by gnbrndn** [comment]
Same error with version 3.1.2. Tried the version 4.0.0-alpha, problem was the `onInit` function was not being called on that version. Peer dependencies and extra config on 3.1.2 would be really helpful.

**Comment by phuongEts** [comment]
> This is the line causing the issue in version "3.1.2". Causing `nameof is not defined`.
> 
> https://github.com/thanhtunguet/grapesjs-react/blob/b516f45e127c0a5e323f9cc9b2b1a89436e88687/src/Editor/Editor.tsx#L130

i upgrade to version 4.0.0-alpha, but same error with old version

**Comment by thanhtunguet** [comment]
> > This is the line causing the issue in version "3.1.2". Causing `nameof is not defined`.
> > https://github.com/thanhtunguet/grapesjs-react/blob/b516f45e127c0a5e323f9cc9b2b1a89436e88687/src/Editor/Editor.tsx#L130
> 
> i upgrade to version 4.0.0-alpha, but same error with old version

Have you tried to downgrade to v3.1.1 or the older versions?

**Comment by thanhtunguet** [comment]
> > Object.defineProperty(window, nameof(GrapesJS), GrapesJS);

This line is in v3. In v4 I do not use the nameof macro.

**Comment by Niush** [comment]
Works when downgrading to v3.1.1
Works when updating to 4.0.0-alpha, but causes other breaking changes. (e.g. Editor not exported)

@PhuongTntechs, **Downgrading to v3.1.1 is best option.**

**Comment by thanhtunguet** [comment]
> Works when downgrading to v3.1.1
> Works when updating to 4.0.0-alpha, but causes other breaking changes. (e.g. Editor not exported)
> 
> @PhuongTntechs, **Downgrading to v3.1.1 is best option.**

Thank you @Niush, I will try to fix this v3 issue soon.

**Comment by thanhtunguet** [comment]
I created a patch 3.1.3 for v3. Commit your changes before try upgrading the package to v3.1.3 to check this issue.
