### ISSUE TITLE
Using GrapeJS on nextjs

### ISSUE THREAD

**Issue by eyroooon** [thanhtunguet/grapesjs-react#50]
Some of the css was not working properly for example the .gjs-cv-canvas was not working. 

This is the screenshot of my grapejs page in nextjs

![image](https://user-images.githubusercontent.com/64449714/119433019-f3783080-bd47-11eb-983c-0a5590a46292.png)

**Comment by thanhtunguet** [comment]
> Some of the css was not working properly for example the .gjs-cv-canvas was not working.
> 
> This is the screenshot of my grapejs page in nextjs
> 
> ![image](https://user-images.githubusercontent.com/64449714/119433019-f3783080-bd47-11eb-983c-0a5590a46292.png)

I know not much about NextJS.  I think the problem occurred because Next has modified the css file while bundling it. You may try to add a link tag into head tag of HTML document to load grapesjs css directly on browser.

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/grapesjs/0.17.4/css/grapes.min.css" integrity="sha512-lwxAeLCxFtX4NpYrI8V8uNyOysWjUPZNg1ZIP5mmdGkanQ9oWCkNiOyRVAqIrdhPdfBqpVYGHwdEVFtkzA8XBQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```
