### ISSUE TITLE
Window is not defined (grapesjs-react + Next JS)

### ISSUE THREAD

**Issue by YosaRama** [thanhtunguet/grapesjs-react#51]
<img width="1061" alt="Screen Shot 2021-07-05 at 15 17 48" src="https://user-images.githubusercontent.com/67961793/124432397-2b8d7d00-dda4-11eb-814e-8ab2e1c4df9d.png">

I got this problem, how to solve that ?, 

<img width="1168" alt="Screen Shot 2021-07-05 at 15 18 31" src="https://user-images.githubusercontent.com/67961793/124432480-42cc6a80-dda4-11eb-9189-6f4c84faed04.png">

this is my code, please help me for fix this 

Thanks !

**Comment by thanhtunguet** [comment]
> <img alt="Screen Shot 2021-07-05 at 15 17 48" width="1061" src="https://user-images.githubusercontent.com/67961793/124432397-2b8d7d00-dda4-11eb-814e-8ab2e1c4df9d.png">
> 
> I got this problem, how to solve that ?,
> 
> <img alt="Screen Shot 2021-07-05 at 15 18 31" width="1168" src="https://user-images.githubusercontent.com/67961793/124432480-42cc6a80-dda4-11eb-9189-6f4c84faed04.png">
> 
> this is my code, please help me for fix this
> 
> Thanks !

This library includes CSS and browser APIs so that you can not use it in server side.
Only use it in client side.

**Comment by YosaRama** [comment]
Oh okay Thanks for the respond, and for this V.4 how can I add blocks, components, commands or all about grapes.js stuff ?, because I can't find any details for this one on README file.

Thanks !

**Comment by thanhtunguet** [comment]
> Oh okay Thanks for the respond, and for this V.4 how can I add blocks, components, commands or all about grapes.js stuff ?, because I can't find any details for this one on README file.
> 
> Thanks !

Pass grapesjs options (storage manager, block manager, ...) as props to the editor component. Except `id`, `onInit`, `onDestroy`, all the rest props will be passed as options on editor initialization.
You may read the offficial grapesjs documentation for option's details.

**Comment by YosaRama** [comment]
Oke, Thank You so much for respond.
